config/routes.rb
Rails.application.routes.draw do
  
  post 'payments/create'
  mount ActionCable.server => '/cable'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]


  post 'simple_pages/thank_you'

  root 'simple_pages#landing_page'

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true

  has_many :orders
  has_many :comments

  def self.search(search_term)
    if Rails.env.development?
      Product.where("name LIKE ?", "%#{search_term}%")
    else
      Product.where("name ilike ?", "%#{search_term}%")
    end
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_asc.first
  end

  def comment_count
    comments.length
  end

  def average_rating
    comments.average(:rating).to_f
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
      # return our filtered list here
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], per_page: 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :condition, :dimension, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <%= render comment %>
    <% end %>

    <%= will_paginate @comments, previous_label: "Oldest", next_label: "Newest" %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition, id: :product_condition, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :dimension %>
    <%= form.text_field :dimension, id: :product_dimension, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_field, class:"form-control" %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>

    <p><strong>Rating</strong><p/>
      <div class="rating"></div>
    </p>

    <p class="actions">
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
  <div class="col-sm-3">
    <%= link_to(image_tag(product.image_url, class: "img-fluid index-product-img"), product_path(:id => product.id), :method => :get) %>
    <div class="index-product-name">
      <%= product.name %>
    </div>
    <div class="index-product-info">
      <div class="index-product-price">
        &#128178;<%= product.price %>
      </div>
      <button class="btn add-to-cart-btn">
        <span class="glyphicon glyphicon-plus"></span>
        <span class="glyphicon glyphicon-shopping-cart"></span>
      </button>
    </div>
  </div>
<% end %>

app/views/products/_secondary_nav_products.html.erb
<div class="sec-nav-div">
  <div class="row sec-nav">
    <span class="col-4"><%= link_to "| Home |", root_path, class: "sec-nav-link" %></span>
    <span class="col-4"><%= link_to "| Products |", products_path %></span>
    <span class="col-4"><%= link_to "| Contact |", simple_pages_contact_path %></span>
  </div>

  <div class="sec-nav-search">
    <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
    <%= form.text_field :q, id: 'q', value: params[:q] %>
    <%= form.submit 'Search' %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="simple-page-title">Products</h2>

<%= render "secondary_nav_products" %>

<div class="container">
  <div class="row">
    <!--The following line represets the @products array being iterrated through
    the _product partial(No need for .each method, Rails does everything for you)-->
    <% cache(cache_key_for_products) do %>
      <%= render @products %>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<% cache @product do %>

  <div class="row">

    <div class="col-sm-12 col-md-7 product-show-img">
    <%= image_tag(@product.image_url, width: "350", class: "img-zoom", data_zoom_image: @product.image_url) %>
    </div>

    <div class="col-sm-12 col-md-5 product-info">

      <div class="product-show-name">
          <%= @product.name %>
      </div>


      <div class="rated average-rating" data-score="<%=@product.average_rating %>">Out of <%= @product.comment_count %> </div>

      <div class="product-show-buy row">
        <div class="col-sm-6">
          <p>
            Condition:
            <strong><%= @product.condition %></strong>
          </p>
          <p>
            Price:
            <strong><%= @product.price %></strong>
          </p>
        </div>
        <span class="col-sm-6 payment-button">
          <%= form_with(url: '/payments/create') do |form| %>
          <%= hidden_field_tag(:product_id, @product.id) %>
          <%= render partial: "shared/stripe_checkout_button" %>
          <% end %>
        </span>

      </div>

      <p>
        <u>Description:</u>
        <%= @product.description %>
      </p>


      <p>
        <u>Dimension:</u>
        <%= @product.dimension %>
      </p>


    </div>
  </div>

<% end %>


<%= render 'new_comment' %>

<div class="alert alert-info" style="disply:none" role="alert">A new comment was posted!</div>

<%= render 'comments' %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>